### ISSUE TITLE
vendor not found

### ISSUE THREAD

**Issue by huanghjA** [gentritabazi01/Vue-Lumen-Starter#16]
Hi, dear author:

In /back/bootstrap/app.php line3,
`require_once __DIR__.'/../vendor/autoload.php';`
However, error occured as it can't find the `vendor/autoload.php`.

**Comment by gentritabazi01** [comment]
Hello,

Nothing wrong here ?

Check original file in lumen github:

https://github.com/laravel/lumen/blob/8.x/bootstrap/app.php#L3

**Comment by huanghjA** [comment]
Thanks,

It seems that I should run `composer install` in dir ./back in order to generate the `vendor/autoload.php`.

**Comment by huanghjA** [comment]
`{"success":false,"status":404,"message":"Not Found.","exception":"Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException in \/Users\/huanghj\/Project\/Vue-Lumen-Starter\/back\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php:230\nStack trace:\n#0 \/Users\/huanghj\/Project\/Vue-Lumen-Starter\/back\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(170): Laravel\\Lumen\\Application->handleDispatcherResponse(Array)\n#1 [internal function]: Laravel\\Lumen\\Application->Laravel\\Lumen\\Concerns\\{closure}(Object(Laravel\\Lumen\\Http\\Request))\n#2 \/Users\/huanghj\/Project\/Vue-Lumen-Starter\/back\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(48): call_user_func(Object(Closure), Object(Laravel\\Lumen\\Http\\Request))\n#3 \/Users\/huanghj\/Project\/Vue-Lumen-Starter\/back\/vendor\/fruitcake\/laravel-cors\/src\/HandleCors.php(37): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))\n#4 \/Users\/huanghj\/Project\/Vue-Lumen-Starter\/back\/vendor\/illuminate\/pipeline\/Pipeline.php(167): Fruitcake\\Cors\\HandleCors->handle(Object(Laravel\\Lumen\\Http\\Request), Object(Closure))\n#5 [internal function]: Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Laravel\\Lumen\\Http\\Request))\n#6 \/Users\/huanghj\/Project\/Vue-Lumen-Starter\/back\/vendor\/laravel\/lumen-framework\/src\/Routing\/Pipeline.php(30): call_user_func(Object(Closure), Object(Laravel\\Lumen\\Http\\Request))\n#7 \/Users\/huanghj\/Project\/Vue-Lumen-Starter\/back\/vendor\/illuminate\/pipeline\/Pipeline.php(103): Laravel\\Lumen\\Routing\\Pipeline->Laravel\\Lumen\\Routing\\{closure}(Object(Laravel\\Lumen\\Http\\Request))\n#8 \/Users\/huanghj\/Project\/Vue-Lumen-Starter\/back\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(423): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))\n#9 \/Users\/huanghj\/Project\/Vue-Lumen-Starter\/back\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(172): Laravel\\Lumen\\Application->sendThroughPipeline(Array, Object(Closure))\n#10 \/Users\/huanghj\/Project\/Vue-Lumen-Starter\/back\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php(109): Laravel\\Lumen\\Application->dispatch(NULL)\n#11 \/Users\/huanghj\/Project\/Vue-Lumen-Starter\/back\/public\/index.php(28): Laravel\\Lumen\\Application->run()\n#12 {main}","line":230,"file":"\/Users\/huanghj\/Project\/Vue-Lumen-Starter\/back\/vendor\/laravel\/lumen-framework\/src\/Concerns\/RoutesRequests.php"}`

I have finished the operations successfully and I run the comment in back-end as `php -S localhost:8000 -t public` .

However, the website localhost:8000 display errors as above. I am a new starter in lumen and Can you help me?

**Comment by gentritabazi01** [comment]
Did you set correct url in `front/.env` at `VUE_APP_BACKEND_URL` ?

**Comment by huanghjA** [comment]
Yes, it is correctly sent.

I think that it has something wrong with back-end as running `php -S localhost:8000 -t public` and the back-end website gives me a long error instead of the lumen version.
