### ISSUE TITLE
what should my VUE_APP_BACKEND_URL be?

### ISSUE THREAD

**Issue by james0r** [gentritabazi01/Vue-Lumen-Starter#24]
VUE_APP_BACKEND_URL='http://localhost/lumen-vue/back/public/api'

is what it would match up given the right webroot, but after installation there is no api directory in /back/public

**Comment by gentritabazi01** [comment]
Look [routes.php](https://github.com/gentritabazi01/Vue-Lumen-Starter/blob/master/back/modules/Users/routes.php), all have [prefix](https://github.com/gentritabazi01/Vue-Lumen-Starter/blob/master/back/modules/Users/Providers/UserServiceProvider.php#L27).

**Comment by james0r** [comment]
i'm getting 403 forbidden at every endpoint i try and hit.

do i need a different nginx config to work with this? this is what i currently have:

```
server {
    listen       80;
    server_name  localhost;
    root   /usr/local/var/www;

    #charset koi8-r;

    #access_log  logs/host.access.log  main;

    location / {
        index  index.html index.php;
    }

    #error_page  404              /404.html;

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
	location ~ \.php$ {
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass 127.0.0.1:9074;
        fastcgi_index index.php;
        include fastcgi_params;
	}

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    location ~ /\.ht {
       deny  all;
    }
}```

**Comment by gentritabazi01** [comment]
Why you are not using apache ?

Or just:  `php -S localhost:8000 -t ./public` ?

**Comment by james0r** [comment]
okay i'll try that thanks
