### ISSUE TITLE
Questions/Suggestions

### ISSUE THREAD

**Issue by SuperlativeEntity** [gentritabazi01/Vue-Lumen-Starter#4]
I managed to get everything set up and it works great!

**Question 1**
I see that web.php is used for routes. Shouldn't api.php be used instead?

**Question 2**
Would you consider doing a basic CRUD example? Including the following components:
a grid that paginates server-side
select dropdown
checkboxes
radio buttons
a model (maybe users?) with tabs: e.g. [basic info] [contact details]

The CRUD model could use eloquent resources and perhaps the usage of the repository pattern?

**Question 3**
Would you consider integrating spatie/permission? For roles and permissions

**Question 4**
Frontend: Is it safe to store the token in local storage? Can a user manipulate the token client-side?

The starter is great, but with the suggestions above you'd have a more complete real-world starter.

**Comment by gentritabazi01** [comment]
Thank you very much.

**Question 1**:
Yes you are right.

**Question 2**:
No i don't want to give examples i want this Starter to be clean.

**Question 3**:
No.

**Question 4**:
I will change to state (Vuex).

**Comment by SuperlativeEntity** [comment]
"No i don't want to give examples i want this Starter to be clean." and " No to spatie/permission"

You could maybe create a scaffolding command that can add these in like Laravel has auth scaffolding.
That way you can still keep the base clean and allow people to scaffold a real-world CRUD example and build from there.
