### ISSUE TITLE
Sidebar Collapse not Working 

### ISSUE THREAD

**Issue by AliVeseli** [gentritabazi01/Vue-Lumen-Starter#5]
The Button for collapsing the side menu not working, also in mobile it stays open and there is no way to close it !

**Comment by gentritabazi01** [comment]
Thanks for report, i will check.

**Comment by gentritabazi01** [comment]
https://github.com/gentritabazi01/Vue-Lumen-Starter/commit/8f790f79109c672c0f2acda610774aa218e79e9b
